// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIg7N7pIdYElPkfA40-epRabheGMikrGc',
    appId: '1:1072322187200:web:0a2f45bec1c4ca36414225',
    messagingSenderId: '1072322187200',
    projectId: 'retail-app-mvp',
    authDomain: 'retail-app-mvp.firebaseapp.com',
    storageBucket: 'retail-app-mvp.firebasestorage.app',
    measurementId: 'G-6EQHZD1XNB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC61C2iwn7CP6ouMg6U6rhzrnQs1KTaT_Y',
    appId: '1:1072322187200:android:c2442e40ebc43e6f414225',
    messagingSenderId: '1072322187200',
    projectId: 'retail-app-mvp',
    storageBucket: 'retail-app-mvp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0II0nBC_33euy9XecKD_Y4IzLzI0II7Q',
    appId: '1:1072322187200:ios:2879031bc4b08536414225',
    messagingSenderId: '1072322187200',
    projectId: 'retail-app-mvp',
    storageBucket: 'retail-app-mvp.firebasestorage.app',
    androidClientId: '1072322187200-lpet8rr7ul6ps56vrsfarbm4vus6hhvj.apps.googleusercontent.com',
    iosClientId: '1072322187200-amgjtuhin0vkacnmhtb0ndbts898b2m7.apps.googleusercontent.com',
    iosBundleId: 'com.example.retailApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0II0nBC_33euy9XecKD_Y4IzLzI0II7Q',
    appId: '1:1072322187200:ios:2879031bc4b08536414225',
    messagingSenderId: '1072322187200',
    projectId: 'retail-app-mvp',
    storageBucket: 'retail-app-mvp.firebasestorage.app',
    androidClientId: '1072322187200-lpet8rr7ul6ps56vrsfarbm4vus6hhvj.apps.googleusercontent.com',
    iosClientId: '1072322187200-amgjtuhin0vkacnmhtb0ndbts898b2m7.apps.googleusercontent.com',
    iosBundleId: 'com.example.retailApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIg7N7pIdYElPkfA40-epRabheGMikrGc',
    appId: '1:1072322187200:web:1fb7f70de18547ab414225',
    messagingSenderId: '1072322187200',
    projectId: 'retail-app-mvp',
    authDomain: 'retail-app-mvp.firebaseapp.com',
    storageBucket: 'retail-app-mvp.firebasestorage.app',
    measurementId: 'G-7V2FX81DWN',
  );
}
